### ISSUE TITLE
条件中前缀和后缀只的是什么！

### ISSUE THREAD

**Issue by xllxll** [Bynil/MessageJudge#2]
条件中前缀和后缀只的是什么！

**Comment by gexiao** [comment]
`条件中前缀和后缀只的是什么！` 这句话中，「条件中」就是一个前缀，「是什么！」就是一个后缀。

更简单的理解：前缀指以什么文字开头，后缀指以什么文字结束。

**Comment by xllxll** [comment]
软件比大牌做的都好，很实用。下了几个对比发现就这个比较全面。唯一看到有一个类似的短信拦截没有白名单概念的，但是它多了一个iCloud备份规则，导入iCloud备份，从iCloud导出备份。这个你可以借鉴下。叫做“短信防火墙”。期待加入更新。辛苦了

**Comment by gexiao** [comment]
代码写好了，下个版本的更新将加入 iCloud 的备份和恢复功能。

**Comment by xllxll** [comment]
完美！
