### ISSUE TITLE
并没有看见此项：打开设置里的拦截开关: 设置 -> 信息 -> 未知与垃圾信息 -> 短信过滤 -> MessageJudge.

### ISSUE THREAD

**Issue by senlinmuvs** [Bynil/MessageJudge#3]
并没有看见此项：打开设置里的拦截开关: 设置 -> 信息 -> 未知与垃圾信息 -> 短信过滤 -> MessageJudge.

**Comment by gexiao** [comment]
重启手机，把 App 删了重新装一次看看。不行的话我也没办法了，系统设置和 App 没有关系。

**Comment by senlinmuvs** [comment]
> 重启手机，把 App 删了重新装一次看看。不行的话我也没办法了，系统设置和 App 没有关系。

嗯。重新装也一样，我用百度的安全卫士在设置有
